import { Train, LiveStatus, WeatherData, GeoPOI, ElevationPoint } from '@/types';

export const POPULAR_TRAINS: Train[] = [
  {
    id: '22436',
    number: '22436',
    name: 'Vande Bharat Express',
    type: 'Vande Bharat',
    source: 'New Delhi (NDLS)',
    destination: 'Varanasi Junction (BSB)',
    daysOfOperation: ['Mon', 'Tue', 'Wed', 'Fri', 'Sat', 'Sun'],
    route: {
      source: 'New Delhi (NDLS)',
      destination: 'Varanasi Junction (BSB)',
      totalDistanceKm: 759,
      totalDurationMinutes: 480, // 8 hrs
      stations: [
        {
          id: 'ndls',
          name: 'New Delhi',
          code: 'NDLS',
          lat: 28.6415,
          lng: 77.2197,
          scheduledArrival: '06:00',
          scheduledDeparture: '06:00',
          actualArrival: '06:00',
          actualDeparture: '06:00',
          delayMinutes: 0,
          distanceFromStartKm: 0,
          elevationMeters: 216,
          platform: '16',
          status: 'passed',
        },
        {
          id: 'cnb',
          name: 'Kanpur Central',
          code: 'CNB',
          lat: 26.4542,
          lng: 80.3502,
          scheduledArrival: '10:08',
          scheduledDeparture: '10:10',
          actualArrival: '10:12',
          actualDeparture: '10:14',
          delayMinutes: 4,
          distanceFromStartKm: 440,
          elevationMeters: 126,
          platform: '5',
          status: 'passed',
        },
        {
          id: 'pryj',
          name: 'Prayagraj Junction',
          code: 'PRYJ',
          lat: 25.4484,
          lng: 81.8324,
          scheduledArrival: '12:08',
          scheduledDeparture: '12:10',
          actualArrival: '12:10',
          actualDeparture: '12:12',
          delayMinutes: 2,
          distanceFromStartKm: 634,
          elevationMeters: 98,
          platform: '6',
          status: 'current',
        },
        {
          id: 'bsb',
          name: 'Varanasi Junction',
          code: 'BSB',
          lat: 25.3216,
          lng: 82.9876,
          scheduledArrival: '14:00',
          scheduledDeparture: '14:00',
          delayMinutes: 0,
          distanceFromStartKm: 759,
          elevationMeters: 76,
          platform: '1',
          status: 'upcoming',
        },
      ],
    },
  },
  {
    id: '12951',
    number: '12951',
    name: 'Mumbai Rajdhani Express',
    type: 'Rajdhani',
    source: 'Mumbai Central (MMCT)',
    destination: 'New Delhi (NDLS)',
    daysOfOperation: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
    route: {
      source: 'Mumbai Central (MMCT)',
      destination: 'New Delhi (NDLS)',
      totalDistanceKm: 1384,
      totalDurationMinutes: 935, // 15h 35m
      stations: [
        {
          id: 'mmct',
          name: 'Mumbai Central',
          code: 'MMCT',
          lat: 18.9696,
          lng: 72.8193,
          scheduledArrival: '17:00',
          scheduledDeparture: '17:00',
          actualArrival: '17:00',
          actualDeparture: '17:00',
          delayMinutes: 0,
          distanceFromStartKm: 0,
          elevationMeters: 8,
          platform: '1',
          status: 'passed',
        },
        {
          id: 'st',
          name: 'Surat',
          code: 'ST',
          lat: 21.2035,
          lng: 72.8392,
          scheduledArrival: '19:43',
          scheduledDeparture: '19:48',
          actualArrival: '19:45',
          actualDeparture: '19:50',
          delayMinutes: 2,
          distanceFromStartKm: 263,
          elevationMeters: 13,
          platform: '1',
          status: 'passed',
        },
        {
          id: 'brc',
          name: 'Vadodara Junction',
          code: 'BRC',
          lat: 22.3107,
          lng: 73.1812,
          scheduledArrival: '21:06',
          scheduledDeparture: '21:16',
          actualArrival: '21:12',
          actualDeparture: '21:22',
          delayMinutes: 6,
          distanceFromStartKm: 393,
          elevationMeters: 36,
          platform: '2',
          status: 'passed',
        },
        {
          id: 'rtm',
          name: 'Ratlam Junction',
          code: 'RTM',
          lat: 23.3344,
          lng: 75.0371,
          scheduledArrival: '00:25',
          scheduledDeparture: '00:28',
          actualArrival: '00:30',
          actualDeparture: '00:33',
          delayMinutes: 5,
          distanceFromStartKm: 653,
          elevationMeters: 494,
          platform: '5',
          status: 'passed',
        },
        {
          id: 'kota',
          name: 'Kota Junction',
          code: 'KOTA',
          lat: 25.2201,
          lng: 75.8648,
          scheduledArrival: '03:15',
          scheduledDeparture: '03:25',
          actualArrival: '03:20',
          actualDeparture: '03:30',
          delayMinutes: 5,
          distanceFromStartKm: 920,
          elevationMeters: 253,
          platform: '1',
          status: 'current',
        },
        {
          id: 'ndls_raj',
          name: 'New Delhi',
          code: 'NDLS',
          lat: 28.6415,
          lng: 77.2197,
          scheduledArrival: '08:32',
          scheduledDeparture: '08:32',
          delayMinutes: 5,
          distanceFromStartKm: 1384,
          elevationMeters: 216,
          platform: '4',
          status: 'upcoming',
        },
      ],
    },
  },
  {
    id: '12002',
    number: '12002',
    name: 'Bhopal Shatabdi Express',
    type: 'Shatabdi',
    source: 'New Delhi (NDLS)',
    destination: 'Rani Kamlapati (RKMP)',
    daysOfOperation: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
    route: {
      source: 'New Delhi (NDLS)',
      destination: 'Rani Kamlapati (RKMP)',
      totalDistanceKm: 708,
      totalDurationMinutes: 510,
      stations: [
        {
          id: 'ndls_s',
          name: 'New Delhi',
          code: 'NDLS',
          lat: 28.6415,
          lng: 77.2197,
          scheduledArrival: '06:00',
          scheduledDeparture: '06:00',
          actualArrival: '06:00',
          actualDeparture: '06:00',
          delayMinutes: 0,
          distanceFromStartKm: 0,
          elevationMeters: 216,
          platform: '1',
          status: 'passed',
        },
        {
          id: 'agc',
          name: 'Agra Cantt',
          code: 'AGC',
          lat: 27.1587,
          lng: 77.9942,
          scheduledArrival: '07:50',
          scheduledDeparture: '07:55',
          actualArrival: '07:50',
          actualDeparture: '07:55',
          delayMinutes: 0,
          distanceFromStartKm: 195,
          elevationMeters: 167,
          platform: '1',
          status: 'passed',
        },
        {
          id: 'gwl',
          name: 'Gwalior Junction',
          code: 'GWL',
          lat: 26.2183,
          lng: 78.1828,
          scheduledArrival: '09:23',
          scheduledDeparture: '09:28',
          actualArrival: '09:25',
          actualDeparture: '09:30',
          delayMinutes: 2,
          distanceFromStartKm: 313,
          elevationMeters: 212,
          platform: '1',
          status: 'passed',
        },
        {
          id: 'vglj',
          name: 'VGL Jhansi Junction',
          code: 'VGLJ',
          lat: 25.4484,
          lng: 78.5685,
          scheduledArrival: '10:45',
          scheduledDeparture: '10:50',
          actualArrival: '10:48',
          actualDeparture: '10:53',
          delayMinutes: 3,
          distanceFromStartKm: 411,
          elevationMeters: 258,
          platform: '2',
          status: 'current',
        },
        {
          id: 'rkmp',
          name: 'Rani Kamlapati',
          code: 'RKMP',
          lat: 23.2201,
          lng: 77.4385,
          scheduledArrival: '14:30',
          scheduledDeparture: '14:30',
          delayMinutes: 0,
          distanceFromStartKm: 708,
          elevationMeters: 527,
          platform: '1',
          status: 'upcoming',
        },
      ],
    },
  },
  {
    id: '12626',
    number: '12626',
    name: 'Kerala Express',
    type: 'Superfast',
    source: 'New Delhi (NDLS)',
    destination: 'Thiruvananthapuram (TVC)',
    daysOfOperation: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
    route: {
      source: 'New Delhi (NDLS)',
      destination: 'Thiruvananthapuram (TVC)',
      totalDistanceKm: 3031,
      totalDurationMinutes: 2970,
      stations: [
        {
          id: 'ndls_k',
          name: 'New Delhi',
          code: 'NDLS',
          lat: 28.6415,
          lng: 77.2197,
          scheduledArrival: '20:10',
          scheduledDeparture: '20:10',
          actualArrival: '20:10',
          actualDeparture: '20:10',
          delayMinutes: 0,
          distanceFromStartKm: 0,
          elevationMeters: 216,
          platform: '3',
          status: 'passed',
        },
        {
          id: 'bpl_k',
          name: 'Bhopal Junction',
          code: 'BPL',
          lat: 23.2599,
          lng: 77.4126,
          scheduledArrival: '05:30',
          scheduledDeparture: '05:40',
          actualArrival: '05:42',
          actualDeparture: '05:52',
          delayMinutes: 12,
          distanceFromStartKm: 701,
          elevationMeters: 523,
          platform: '1',
          status: 'passed',
        },
        {
          id: 'ngp',
          name: 'Nagpur Junction',
          code: 'NGP',
          lat: 21.1524,
          lng: 79.0888,
          scheduledArrival: '11:45',
          scheduledDeparture: '11:50',
          actualArrival: '11:58',
          actualDeparture: '12:03',
          delayMinutes: 13,
          distanceFromStartKm: 1091,
          elevationMeters: 312,
          platform: '2',
          status: 'current',
        },
        {
          id: 'tvc',
          name: 'Thiruvananthapuram Central',
          code: 'TVC',
          lat: 8.4875,
          lng: 76.9525,
          scheduledArrival: '18:00',
          scheduledDeparture: '18:00',
          delayMinutes: 10,
          distanceFromStartKm: 3031,
          elevationMeters: 10,
          platform: '1',
          status: 'upcoming',
        },
      ],
    },
  },
];

export const MOCK_LIVE_STATUS: Record<string, LiveStatus> = {
  '22436': {
    trainId: '22436',
    trainNumber: '22436',
    trainName: 'Vande Bharat Express',
    status: 'On Time',
    delayMinutes: 2,
    currentStation: POPULAR_TRAINS[0].route.stations[2], // Prayagraj
    nextStation: POPULAR_TRAINS[0].route.stations[3], // Varanasi
    previousStation: POPULAR_TRAINS[0].route.stations[1], // Kanpur
    currentLocation: {
      lat: 25.4484,
      lng: 81.8324,
      speedKmh: 128,
      heading: 95,
    },
    progressPercentage: 83.5,
    distanceCoveredKm: 634,
    remainingDistanceKm: 125,
    lastUpdated: 'Just now',
    etaDestination: '14:02 PM',
  },
  '12951': {
    trainId: '12951',
    trainNumber: '12951',
    trainName: 'Mumbai Rajdhani Express',
    status: 'Delayed',
    delayMinutes: 5,
    currentStation: POPULAR_TRAINS[1].route.stations[4], // Kota
    nextStation: POPULAR_TRAINS[1].route.stations[5], // New Delhi
    previousStation: POPULAR_TRAINS[1].route.stations[3], // Ratlam
    currentLocation: {
      lat: 25.2201,
      lng: 75.8648,
      speedKmh: 130,
      heading: 25,
    },
    progressPercentage: 66.4,
    distanceCoveredKm: 920,
    remainingDistanceKm: 464,
    lastUpdated: '10 sec ago',
    etaDestination: '08:37 AM',
  },
  '12002': {
    trainId: '12002',
    trainNumber: '12002',
    trainName: 'Bhopal Shatabdi Express',
    status: 'On Time',
    delayMinutes: 3,
    currentStation: POPULAR_TRAINS[2].route.stations[3], // Jhansi
    nextStation: POPULAR_TRAINS[2].route.stations[4], // RKMP
    previousStation: POPULAR_TRAINS[2].route.stations[2], // Gwalior
    currentLocation: {
      lat: 25.4484,
      lng: 78.5685,
      speedKmh: 140,
      heading: 175,
    },
    progressPercentage: 58.0,
    distanceCoveredKm: 411,
    remainingDistanceKm: 297,
    lastUpdated: '5 sec ago',
    etaDestination: '14:33 PM',
  },
  '12626': {
    trainId: '12626',
    trainNumber: '12626',
    trainName: 'Kerala Express',
    status: 'Delayed',
    delayMinutes: 13,
    currentStation: POPULAR_TRAINS[3].route.stations[2], // Nagpur
    nextStation: POPULAR_TRAINS[3].route.stations[3], // TVC
    previousStation: POPULAR_TRAINS[3].route.stations[1], // Bhopal
    currentLocation: {
      lat: 21.1524,
      lng: 79.0888,
      speedKmh: 110,
      heading: 160,
    },
    progressPercentage: 36.0,
    distanceCoveredKm: 1091,
    remainingDistanceKm: 1940,
    lastUpdated: '12 sec ago',
    etaDestination: '18:13 PM',
  },
};

export const MOCK_WEATHER: Record<string, WeatherData> = {
  PRYJ: {
    stationCode: 'PRYJ',
    stationName: 'Prayagraj Junction',
    temperature: 31,
    condition: 'Partly Cloudy',
    humidity: 62,
    windSpeedKmh: 14,
    rainProbability: 15,
    icon: 'partly-cloudy',
    forecast: [
      { time: '13:00', temp: 32, condition: 'Sunny' },
      { time: '14:00', temp: 33, condition: 'Sunny' },
      { time: '15:00', temp: 31, condition: 'Partly Cloudy' },
      { time: '16:00', temp: 29, condition: 'Rain' },
    ],
  },
  BSB: {
    stationCode: 'BSB',
    stationName: 'Varanasi Junction',
    temperature: 30,
    condition: 'Sunny',
    humidity: 58,
    windSpeedKmh: 11,
    rainProbability: 5,
    icon: 'sunny',
    forecast: [
      { time: '14:00', temp: 32, condition: 'Sunny' },
      { time: '15:00', temp: 31, condition: 'Sunny' },
      { time: '16:00', temp: 30, condition: 'Clear' },
      { time: '17:00', temp: 28, condition: 'Clear' },
    ],
  },
  KOTA: {
    stationCode: 'KOTA',
    stationName: 'Kota Junction',
    temperature: 34,
    condition: 'Clear',
    humidity: 45,
    windSpeedKmh: 18,
    rainProbability: 0,
    icon: 'sunny',
    forecast: [
      { time: '04:00', temp: 30, condition: 'Clear' },
      { time: '05:00', temp: 29, condition: 'Clear' },
      { time: '06:00', temp: 31, condition: 'Sunny' },
    ],
  },
  NDLS: {
    stationCode: 'NDLS',
    stationName: 'New Delhi',
    temperature: 33,
    condition: 'Sunny',
    humidity: 50,
    windSpeedKmh: 16,
    rainProbability: 10,
    icon: 'sunny',
    forecast: [
      { time: '08:00', temp: 30, condition: 'Sunny' },
      { time: '09:00', temp: 32, condition: 'Sunny' },
    ],
  },
};

export const MOCK_GEOGRAPHY: Record<string, GeoPOI[]> = {
  PRYJ: [
    {
      id: 'poi-1',
      name: 'Triveni Sangam (Confluence of Ganga, Yamuna & Saraswati)',
      type: 'river',
      distanceKm: 6.2,
      lat: 25.4286,
      lng: 81.8829,
      description: 'Sacred confluence of rivers Ganga, Yamuna and invisible Saraswati.',
    },
    {
      id: 'poi-2',
      name: 'New Yamuna Bridge',
      type: 'bridge',
      distanceKm: 3.4,
      lat: 25.4385,
      lng: 81.8542,
      description: 'Cable-stayed bridge spanning the Yamuna River.',
    },
    {
      id: 'poi-3',
      name: 'Allahabad Fort',
      type: 'attraction',
      distanceKm: 5.1,
      lat: 25.4312,
      lng: 81.8745,
      description: 'Historic 16th century Mughal fort built by Emperor Akbar.',
    },
  ],
  KOTA: [
    {
      id: 'poi-4',
      name: 'Chambal River Bridge',
      type: 'bridge',
      distanceKm: 4.8,
      lat: 25.1856,
      lng: 75.8342,
      description: 'Major railway bridge crossing the deep canyon of Chambal River.',
    },
    {
      id: 'poi-5',
      name: 'Kota Railway Tunnel #1',
      type: 'tunnel',
      distanceKm: 18.2,
      lat: 25.0421,
      lng: 75.7612,
      description: 'Scenic rock-cut rail tunnel through Darrah Wildlife Sanctuary.',
    },
  ],
};

export const MOCK_ELEVATIONS: Record<string, ElevationPoint[]> = {
  '22436': [
    { distanceKm: 0, elevationMeters: 216, stationName: 'NDLS' },
    { distanceKm: 150, elevationMeters: 180 },
    { distanceKm: 300, elevationMeters: 145 },
    { distanceKm: 440, elevationMeters: 126, stationName: 'CNB' },
    { distanceKm: 550, elevationMeters: 110 },
    { distanceKm: 634, elevationMeters: 98, stationName: 'PRYJ' },
    { distanceKm: 700, elevationMeters: 85 },
    { distanceKm: 759, elevationMeters: 76, stationName: 'BSB' },
  ],
  '12951': [
    { distanceKm: 0, elevationMeters: 8, stationName: 'MMCT' },
    { distanceKm: 263, elevationMeters: 13, stationName: 'ST' },
    { distanceKm: 393, elevationMeters: 36, stationName: 'BRC' },
    { distanceKm: 520, elevationMeters: 280 },
    { distanceKm: 653, elevationMeters: 494, stationName: 'RTM' },
    { distanceKm: 800, elevationMeters: 360 },
    { distanceKm: 920, elevationMeters: 253, stationName: 'KOTA' },
    { distanceKm: 1150, elevationMeters: 210 },
    { distanceKm: 1384, elevationMeters: 216, stationName: 'NDLS' },
  ],
};
